name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Thundra maven Test Instrumentation
        uses: thundra-io/thundra-maven-test-action@v1
        with:
          apikey: 8b3a961c-e883-4060-80a9-e2aab4568b41
          project_id: f5dd6012-c5fe-45c1-bc6c-8df445be9ed2

          command: mvn clean install
